### ISSUE TITLE
5/8 新規課題についてindex更新とマークダウン新規作成

### ISSUE THREAD

**Issue by akekaneko** [akekaneko/swagger-sample#67]
# 概要(why/what)

5/8の打ち合わせでの新規課題についてのマークダウンを作成する。
インデックスファイルも更新する。

# 解決方法(How)

- タスク一覧

  - [x] index.md のGitHub項目に以下2件インデックスを追加
    - ChangeLogから、変更履歴と変更理由を明確化するためには？
    - リモート側で新規ブランチを作成した場合、ローカルに持ってくる方法はあるか？

  - [x] リンク先のマークダウンファイルを新規作成
    -  [x] GitHubIssueHowToMake.md
    -  [x] GitHubRemoteBranchClone.md

# 開発担当
- 井上さん

# 承認担当
- 金子

# 終了条件
1. index.md から新規ファイルへのリンクを確認する
1. リンク先ファイルが正しく表示される
1. 以下のチェックがONになる

- [x] 井上さんテスト済
- [x] 金子テスト済

# 備考
- 井上さんの課題調査内容も追加ください
- 金子分のmdファイルはのちほど添付しますのでお待ちください

**Comment by akekaneko** [comment]
Issueの内容を修正しますので、少々お待ちください。

**Comment by akekaneko** [comment]
issue-67 ブランチを新規でリモートで作成しました。
こちらのブランチをローカルに落として修正作業をお願いいたします。

**Comment by akekaneko** [comment]
金子作成分の２ファイルを添付します。こちらをご利用ください。
よろしくお願いします。

[0518.zip](https://github.com/akekaneko/swagger-sample/files/988764/0518.zip)

**Comment by teinoue** [comment]
金子さん

以下のファイルをアップしましたのでご確認ください。

## Issue番号
 #67

## アップロードしたファイル名
GitHubIssueHowToMake.md
GitHubRemoteBranchClone.md

## mention
@akekaneko

**Comment by akekaneko** [comment]
アップありがとうございます。
同時に、Issueのタスク一覧の行った作業のチェックボックスをONに変更してみていただけますか？

**Comment by teinoue** [comment]
Issueのタスク一覧の行った作業のチェックボックスをONに変更しました。
関連するところだけチェックしました。

## mention
@akekaneko

**Comment by akekaneko** [comment]
チェックありがとうございます！

オーナーとAssigneeのユーザであればメールが飛ぶので
mentionは省略してOKです。

**Comment by teinoue** [comment]
了解しました。

**Comment by akekaneko** [comment]
マークダウンにミスがありましたので
添付のファイルへ差し替えいただけますか。
次回のコミットのタイミングでOKです。よろしくお願いします。

[GitHubIssueHowToMake.zip](https://github.com/akekaneko/swagger-sample/files/988874/GitHubIssueHowToMake.zip)

**Comment by akekaneko** [comment]
issue-67 ブランチ 更新ファイルへのリンク
- [index.md](../blob/issue-67/index.md)
- [GitHubIssueHowToMake.md](../blob/issue-67/GitHubIssueHowToMake.md)
- [GitHubRemoteBranchClone.md](../blob/issue-67/GitHubRemoteBranchClone.md)

**Comment by teinoue** [comment]
GitHubIssueHowToMake.mdをPushしました。
確認ください。

**Comment by akekaneko** [comment]
差し替えありがとうございます。
最後の改行がGitHubでは崩れるようですが、
今回はいったんこちらで進めてください。

**Comment by teinoue** [comment]
Create Pull Requestをしました。

**Comment by teinoue** [comment]
「[WIP]ファイルのアップロード #67 #68 」Revertしました。

**Comment by teinoue** [comment]
※再度アップロードしました。

金子さん
以下のファイルをアップしましたのでご確認ください。

## 作業内容
タスク一覧の「リンク先のマークダウンファイルを新規作成」項目の対応
Create Pull Requestまでしました。

## アップロードしたファイル名
GitHubIssueHowToMake.md
GitHubRemoteBranchClone.md

**Comment by teinoue** [comment]
Pull RequestでAssainとLabelの設定しました。
また、先行Merge依頼もコメントに記載しました。
宜しくお願いします。

**Comment by teinoue** [comment]
再度Pull Requestしました。

**Comment by akekaneko** [comment]
先行アップが必要のため、以下ファイルの先行マージ済です
GitHubIssueHowToMake.md
GitHubRemoteBranchClone.md

**Comment by teinoue** [comment]
## 作業内容
Issue-67「index.md のGitHub項目に以下2件インデックスを追加」項目のファイルアップロード #73
のCreate Pull Requestしました。

## 備考
リンクは不明のため記載していません。

確認お願いします。

**Comment by akekaneko** [comment]
ファイルのリンク先は先行マージしたファイルとなりますので
以下になります。修正をお願いします。

https://github.com/akekaneko/swagger-sample/blob/master/GitHubIssueHowToMake.md
https://github.com/akekaneko/swagger-sample/blob/master/GitHubRemoteBranchClone.md

**Comment by teinoue** [comment]
## 作業内容
「index.md のGitHub項目に以下2件インデックスを追加」項目のファイルアップロード #73 の
インデックスの更新をしました。

確認お願いします。

**Comment by teinoue** [comment]
「index.md のGitHub項目に以下2件インデックスを追加」項目のファイルアップロード #73 の
インデックスの修正をしました。

確認お願いします。

**Comment by akekaneko** [comment]
さきほどプルリク側でもコメントとかぶりますが
以下問題が発生したようなので、ご確認お願いします！

- #72 プルリクがクローズされている
- masterのindex.mdファイルが更新されている？

**Comment by akekaneko** [comment]
すみません。さきほどのコメント

- #73 のプルリクがクローズされている

でした。訂正します。

**Comment by teinoue** [comment]
終了条件にチェックを入れました。

**Comment by akekaneko** [comment]
マージ完了しましたので、Issueをクローズします。
お疲れさまでした。
